import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { useDispatch } from "react-redux";
import { createPost } from "../redux/PostSlice";


export default function CreatePost() {
  const [title, setTitle] = useState("");
  const [content, setContent] = useState("");
  const [tags, setTags] = useState("");
  const navigate = useNavigate();
  const dispatch = useDispatch();

  const submit = async (e) => {
    e.preventDefault();
    if (!title || !content) return alert("Title and content are required!");
    await dispatch(createPost({ title, content, tags: tags.split(",") }));
    navigate("/");
  };

  const generateDraft = () => {
    setTitle("AI Generated Title Example");
    setContent("This is a draft generated by AI...");
  };

  return (
    <main className="min-h-screen flex items-center justify-center bg-gradient-to-br from-blue-50 to-white">
      <div className="bg-white p-8 rounded-2xl shadow-lg w-full max-w-3xl transform transition-all duration-500 hover:scale-[1.01]">
        <h1 className="text-3xl font-extrabold mb-6 text-blue-700 text-center animate-fade-in">
          ✨ Create a New Post
        </h1>
        <form onSubmit={submit} className="space-y-6 animate-fade-in-up">
          <input
            placeholder="Title"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            className="w-full border border-blue-200 rounded-lg p-3 text-lg transition-all duration-300 focus:border-blue-500 focus:ring-2 focus:ring-blue-200 shadow-sm"
          />
          <textarea
            placeholder="Content"
            value={content}
            onChange={(e) => setContent(e.target.value)}
            className="w-full border border-blue-200 rounded-lg p-3 h-48 transition-all duration-300 focus:border-blue-500 focus:ring-2 focus:ring-blue-200 shadow-sm"
          />
          <input
            placeholder="Tags (comma separated)"
            value={tags}
            onChange={(e) => setTags(e.target.value)}
            className="w-full border border-blue-200 rounded-lg p-3 transition-all duration-300 focus:border-blue-500 focus:ring-2 focus:ring-blue-200 shadow-sm"
          />
          <div className="flex gap-4 pt-2 justify-center">
            <button
              type="submit"
              className="px-6 py-2 cursor-pointer bg-blue-600 text-white font-semibold rounded-lg shadow-md transform transition-all duration-300 hover:bg-blue-700 hover:scale-105 hover:shadow-lg active:scale-95"
            >
              🚀 Publish
            </button>
            <button
              type="button"
              onClick={generateDraft}
              className="px-6 py-2 cursro-pointer bg-slate-600 text-white font-semibold rounded-lg shadow-md transform transition-all duration-300 hover:bg-slate-700 hover:scale-105 hover:shadow-lg active:scale-95"
            >
              🤖 Generate Draft
            </button>
          </div>
        </form>
      </div>
    </main>
  );
}
